#ifndef _CONFIG_FRIENDSHIP0_H_
#define _CONFIG_FRIENDSHIP0_H_

#define BACKPLANE_MAX_CARDS (4U)
#define BACKPLANE_CARDS_INITIALIZER_LIST {Slot(0U),Slot(1U),Slot(2U),Slot(3U)}

#define BACKPLANE_ID_SLOT_0 (0U)
#define BACKPLANE_ID_SLOT_1 (1U)
#define BACKPLANE_ID_SLOT_2 (2U)
#define BACKPLANE_ID_SLOT_3 (3U)

#define BACKPLANE_SINGLE_SLOT_ID_TO_MASK(id) (1U<<(id))

#define BACKPLANE_MASK_SLOT_NONE (0U)
#define BACKPLANE_MASK_SLOT_0 (BACKPLANE_SINGLE_SLOT_ID_TO_MASK(BACKPLANE_ID_SLOT_0))
#define BACKPLANE_MASK_SLOT_1 (BACKPLANE_SINGLE_SLOT_ID_TO_MASK(BACKPLANE_ID_SLOT_1))
#define BACKPLANE_MASK_SLOT_2 (BACKPLANE_SINGLE_SLOT_ID_TO_MASK(BACKPLANE_ID_SLOT_2))
#define BACKPLANE_MASK_SLOT_3 (BACKPLANE_SINGLE_SLOT_ID_TO_MASK(BACKPLANE_ID_SLOT_3))

#endif // _CONFIG_FRIENDSHIP0_H_
