#ifndef _CONFIG_FRIENDSHIP0_H_
#define _CONFIG_FRIENDSHIP0_H_

#define BACKPLANE_MAX_CARDS (4U)
#define BACKPLANE_CARDS_INITIALIZER_LIST {Slot(0U),Slot(1U),Slot(2U),Slot(3U)}


#endif // _CONFIG_FRIENDSHIP0_H_
