# Objects to be used for the physical layer
OBJECTS_PHYSICAL_LAYER=	$(SOURCEDIR)/arch/$(ARCHITECTURE)/PISORegister.o 			\
						$(SOURCEDIR)/arch/$(ARCHITECTURE)/SIPORegister.o			\


# settings to be made by configuration file.
SOURCEDIR=src
ARCHITECTURE=arduino

# Cflags.



all: $(OBJECTS_PHYSICAL_LAYER)

clean:
	rm $(OBJECTS_PHYSICAL_LAYER)

